const quotes = [
  "The best way to get started is to quit talking and begin doing. – Walt Disney",
  "Don’t let yesterday take up too much of today. – Will Rogers",
  "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
  "Success is not in what you have, but who you are. – Bo Bennett",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Do something today that your future self will thank you for.",
  "Push yourself, because no one else is going to do it for you.",
  "Dream bigger. Do bigger.",
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
  "Great things never come from comfort zones.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Little things make big days.",
  "It always seems impossible until it’s done. – Nelson Mandela",
  "Work hard in silence, let your success be your noise. – Frank Ocean",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "The key to success is to focus on goals, not obstacles.",
  "Doubt kills more dreams than failure ever will. – Suzy Kassem",
  "Be so good they can’t ignore you. – Steve Martin",
  "Discipline is doing what needs to be done, even if you don’t want to do it.",
  "You are capable of amazing things.",
  "Your limitation—it’s only your imagination.",
  "Sometimes later becomes never. Do it now.",
  "Great things take time. Be patient.",
  "If you want it, work for it.",
  "Believe you can and you’re halfway there. – Theodore Roosevelt",
  "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
  "Failure is not the opposite of success, it’s part of success. – Arianna Huffington",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "Action is the foundational key to all success. – Pablo Picasso",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "Success doesn’t just find you. You have to go out and get it.",
  "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
  "Don’t wait for opportunity. Create it.",
  "Your future is created by what you do today, not tomorrow.",
  "A little progress each day adds up to big results.",
  "Success is what comes after you stop making excuses.",
  "You don’t need to see the whole staircase, just take the first step. – Martin Luther King Jr.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "Opportunities don’t happen. You create them. – Chris Grosser",
  "Hard work beats talent when talent doesn’t work hard. – Tim Notke",
  "If you’re going through hell, keep going. – Winston Churchill",
  "Don’t limit your challenges. Challenge your limits.",
  "Do what you can with all you have, wherever you are. – Theodore Roosevelt",
  "It’s never too late to be what you might’ve been. – George Eliot",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Nothing will work unless you do. – Maya Angelou",
  "Work until your idols become your rivals.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
  "Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
  "The man who has confidence in himself gains the confidence of others. – Hasidic Proverb",
  "Never give up. Great things take time.",
  "You miss 100% of the shots you don’t take. – Wayne Gretzky",
  "Start small, think big. Don’t worry about too many things at once. – Steve Jobs",
  "Chase the vision, not the money. – Tony Hsieh",
  "Winners are not afraid of losing. But losers are. – Robert Kiyosaki",
  "Learn as if you will live forever, live like you will die tomorrow. – Mahatma Gandhi",
  "No pressure, no diamonds. – Thomas Carlyle",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "I never dreamed about success. I worked for it. – Estée Lauder",
  "It’s not about ideas. It’s about making ideas happen. – Scott Belsky",
  "Don’t be busy, be productive.",
  "Take the risk or lose the chance.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Do it with passion or not at all.",
  "Quality means doing it right when no one is looking. – Henry Ford",
  "A winner is a dreamer who never gives up. – Nelson Mandela",
  "The biggest risk is not taking any risk. – Mark Zuckerberg",
  "To live a creative life, we must lose our fear of being wrong. – Joseph Chilton Pearce",
  "Don’t raise your voice, improve your argument. – Desmond Tutu",
  "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
  "There is no substitute for hard work. – Thomas Edison",
  "You don’t have to be perfect to be amazing.",
  "Strive for progress, not perfection.",
  "Don’t count the days, make the days count. – Muhammad Ali",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "I am not a product of my circumstances. I am a product of my decisions. – Stephen R. Covey",
  "Fall seven times, stand up eight. – Japanese Proverb",
  "If you want to achieve greatness stop asking for permission.",
  "Don’t quit. Suffer now and live the rest of your life as a champion. – Muhammad Ali",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "What seems to us as bitter trials are often blessings in disguise. – Oscar Wilde",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "Don’t tell people your plans. Show them your results.",
  "We generate fears while we sit. We overcome them by action. – Dr. Henry Link",
  "Try not to become a man of success, but rather try to become a man of value. – Albert Einstein",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "If everything was perfect, you would never learn and you would never grow. – Beyoncé",
  "Act as if what you do makes a difference. It does. – William James",
  "Do not wait for the perfect time and place to enter, for you are already onstage. – Unknown",
  "You can't cross the sea merely by standing and staring at the water. – Rabindranath Tagore",
  "You were born to be a player. You were meant to be here. This moment is yours. – Herb Brooks",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Success is not about luck, it’s about work and persistence.",
  "You already have everything you need to build something far bigger than yourself. – Seth Godin",
  "If people are doubting how far you can go, go so far that you can’t hear them anymore. – Michele Ruiz"
];



function generateQuote (){
  const randomIndex = Math.floor(Math.random()*quotes.length);
  document.getElementById('quote').innerText = quotes[randomIndex];
};